steps:
  # Step 1: Zip the source code
  - name: 'ubuntu'
    id: 'Zip source code'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        zip -r app-source.zip . -x "*.git*" "*cloudbuild.yaml*" 

  # Step 2: Create GCE VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create VM'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=20GB
      - --tags=http-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=956387703564-compute@developer.gserviceaccount.com
      - --project=mythic-beanbag-463309-e9

  # Step 3: Copy source zip to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy app-source.zip to VM'
    args:
      - compute
      - scp
      - app-source.zip
      - vij1542044@my-vm-instance:/home/vij1542044
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9

  # Step 4: Create startup script locally
  - name: 'ubuntu'
    id: 'Create startup script'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat << 'EOF' > startup.sh
        #!/bin/bash
        set -e

        # Install required packages
        sudo apt-get update
        sudo apt-get install -y unzip python3 python3-pip

        # Unzip source code
        unzip -o /home/vij1542044/app-source.zip -d /home/vij1542044/app

        # Navigate to app folder and install dependencies if requirements.txt exists
        cd /home/vij1542044/app
        if [ -f requirements.txt ]; then
          pip3 install -r requirements.txt
        fi

        # Run the Python app using nohup in the background
        nohup python3 app.py > output.log 2>&1 &
        EOF

  # Step 5: Copy startup script to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy startup script to VM'
    args:
      - compute
      - scp
      - startup.sh
      - vij1542044@my-vm-instance:/home/vij1542044
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9

  # Step 6: SSH into VM and run startup script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Run startup script on VM'
    args:
      - compute
      - ssh
      - vij1542044@my-vm-instance
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9
      - --command=bash /home/vij1542044/startup.sh

options:
  logging: CLOUD_LOGGING_ONLY
