steps:
  # Step 1: Zip the gcpvm folder
  - name: 'ubuntu'
    id: 'Zip gcpvm folder'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        zip -r app-source.zip . -x "cloudbuild.yaml"

  # Step 2: Create GCE VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create VM'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=20GB
      - --tags=http-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=956387703564-compute@developer.gserviceaccount.com
      - --project=mythic-beanbag-463309-e9

  # Step 3: Copy app-source.zip to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy app-source.zip to VM'
    args:
      - compute
      - scp
      - app-source.zip
      - sajja_vamsi@my-vm-instance:/home/sajja_vamsi
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9

  # Step 4: Create startup script
  - name: 'ubuntu'
    id: 'Create startup script'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat << 'EOF' > startup.sh
        #!/bin/bash
        set -e

        # Install necessary packages
        sudo apt-get update
        sudo apt-get install -y unzip python3 python3-pip

        # Unzip source
        unzip -o /home/sajja_vamsi/app-source.zip -d /home/sajja_vamsi

        # Change to source directory
        cd /home/sajja_vamsi/gcpvm

        # Install Flask directly
        pip3 install flask

        # Run the app in the background
        nohup python3 app.py > app.log 2>&1 &
        EOF

  # Step 5: Copy startup script to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy startup script to VM'
    args:
      - compute
      - scp
      - startup.sh
      - sajja_vamsi@my-vm-instance:/home/sajja_vamsi
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9

  # Step 6: Run startup script on VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Run startup script on VM'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=mythic-beanbag-463309-e9
      - --command=bash /home/sajja_vamsi/startup.sh

options:
  logging: CLOUD_LOGGING_ONLY
